# Generated by Django 6.0.2 on 2026-02-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ayet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metin', models.TextField(verbose_name='Ayet Metni')),
                ('kaynak', models.CharField(max_length=250, verbose_name='Sure/Ayet No')),
                ('ramazan_gunu', models.PositiveIntegerField(unique=True, verbose_name='Ramazan Günü (1-30)')),
            ],
            options={
                'verbose_name': 'Ayet',
                'verbose_name_plural': 'Ayetler',
            },
        ),
        migrations.CreateModel(
            name='Hadis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metin', models.TextField(verbose_name='Hadis Metni')),
                ('kaynak', models.CharField(max_length=250, verbose_name='Hadis Kaynağı')),
                ('ramazan_gunu', models.PositiveIntegerField(unique=True, verbose_name='Ramazan Günü (1-30)')),
            ],
            options={
                'verbose_name': 'Hadis',
                'verbose_name_plural': 'Hadisler',
            },
        ),
        migrations.CreateModel(
            name='NamazVakti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sehir', models.CharField(max_length=100, verbose_name='Şehir')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('imsak', models.TimeField()),
                ('ogle', models.TimeField()),
                ('ikindi', models.TimeField()),
                ('aksam', models.TimeField(verbose_name='İftar (Akşam)')),
                ('yatsi', models.TimeField()),
            ],
            options={
                'verbose_name': 'Namaz Vakti',
                'verbose_name_plural': 'Namaz Vakitleri',
                'unique_together': {('sehir', 'tarih')},
            },
        ),
    ]
